version: '3.8'
services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - 8002:8000
    env_file:
      - stack.env
    networks:
      - cloudflare_default
    
    volumes:
          - primeportal_db_db_data:/var/lib/postgresql/data
          - user_photos:/app/media

volumes:
  primeportal_db_db_data:
  user_photos:

networks:
  cloudflare_default:
    external: true

networks:
  cloudflare_default:
    external: true

networks:
  cloudflare_default:
    external: true
