version: '3.11'
services:
  bot:
    container_name: av-container
    restart: always
    env_file: 
      - stack.env  
    build: 
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    
    networks:
      - network
    
    # volumes:
      # - ./cogs:/app/cogs
      # - ./db:/app/db
      # - ./utils:/app/utils

networks:
  network:
    name: conn
