# Generated by Django 5.0.2 on 2024-02-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_funcionario_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
    ]
