# Generated by Django 5.0.2 on 2024-02-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_funcionario_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='codigo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='site',
            field=models.CharField(default='www.google.com.br/', max_length=150),
        ),
    ]
