# Generated by Django 5.0.2 on 2024-07-26 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 15, 55, 12, 674590, tzinfo=datetime.timezone.utc)),
        ),
    ]
