# Generated by Django 5.0.2 on 2024-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
