# Generated by Django 5.0.2 on 2024-06-30 20:09

import authentication.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cor_logo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, upload_to=authentication.models.salvar_no_diretorio_do_user),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 20, 9, 18, 699337, tzinfo=datetime.timezone.utc)),
        ),
    ]
