# Generated by Django 5.0.2 on 2024-07-28 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 1, 49, 25, 317224, tzinfo=datetime.timezone.utc)),
        ),
    ]
