# Generated by Django 5.0.2 on 2024-05-25 00:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_status_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 0, 15, 51, 431274, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_pagamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
