# Generated by Django 5.0.2 on 2024-06-26 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_data_cobrar_customuser_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 23, 39, 5, 500069, tzinfo=datetime.timezone.utc)),
        ),
    ]
