# Generated by Django 5.0.2 on 2024-06-26 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_data_cobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 23, 39, 33, 297859, tzinfo=datetime.timezone.utc)),
        ),
    ]
