# Generated by Django 5.0.2 on 2024-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateField(blank=True, default='2024-06-30'),
        ),
    ]
