# Generated by Django 5.0.2 on 2024-05-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrcode')),
                ('site', models.CharField(default='https://primeportalbr.com/avaliacao/', max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=300)),
                ('matricula', models.CharField(blank=True, max_length=15, unique=True)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidade.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
