# Generated by Django 5.0.2 on 2024-06-30 18:49

import funcionario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=funcionario.models.salvar_no_diretorio_do_user),
        ),
    ]
