# Generated by Django 5.0.2 on 2024-05-24 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador_unidade', '0001_initial'),
        ('unidade', '0002_alter_unidade_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador_unidade.administradorunidade'),
        ),
    ]
